const ADD_MESSAGE = 'utter/speaker/ADD_MESSAGE'
const ADD_MESSAGE_FULFILLED = 'utter/speaker/ADD_MESSAGE_FULFILLED'
const LOAD_MESSAGES = 'utter/speaker/LOAD_MESSAGES'
const LOAD_MESSAGES_FULFILLED = 'utter/speaker/LOAD_MESSAGES_FULFILLED'
const SET_AUTHOR = 'utter/speaker/SET_AUTHOR'
const SET_FINAL_TRANSCRIPT = 'utter/speaker/SET_FINAL_TRANSCRIPT'
const SET_FINAL_TRANSCRIPT_FULFILLED =
  'utter/speaker/SET_FINAL_TRANSCRIPT_FULFILLED'
const SET_INTERIM_SCRIPT = 'utter/speaker/SET_INTERIM_SCRIPT'
const SET_INTERIM_SCRIPT_FULFILLED =
  'utter/speaker/SET_INTERIM_SCRIPT_FULFILLED'

export {
  ADD_MESSAGE,
  ADD_MESSAGE_FULFILLED,
  LOAD_MESSAGES,
  LOAD_MESSAGES_FULFILLED,
  SET_AUTHOR,
  SET_FINAL_TRANSCRIPT,
  SET_FINAL_TRANSCRIPT_FULFILLED,
  SET_INTERIM_SCRIPT,
  SET_INTERIM_SCRIPT_FULFILLED
}
