const LOAD_QUESTION = 'utter/challenge/LOAD_QUESTION'
const LOAD_QUESTION_FULFILLED = 'utter/challenge/LOAD_QUESTION_FULFILLED'
const LOAD_QUERY = 'utter/pictures/LOAD_QUERY'
const LOAD_QUERY_FULFILLED = 'utter/pictures/LOAD_QUERY_FULFILLED'
const LOAD_ORIGINAL_WORD_LIST = 'utter/pictures/LOAD_ORIGINAL_WORD_LIST'
const LOAD_ORIGINAL_WORD_LIST_FULFILLED =
  'utter/pictures/LOAD_ORIGINAL_WORD_LIST_FULFILLED'
const UPDATE_ORIGINAL_WORD_LIST = 'utter/pictures/UPDATE_ORIGINAL_WORD_LIST'
const UPDATE_ORIGINAL_WORD_LIST_FULFILLED =
  'utter/pictures/UPDATE_ORIGINAL_WORD_LIST_FULFILLED'
const UPDATE_PICTURE = 'utter/pictures/UPDATE_PICTURE'
const UPDATE_PICTURE_FULFILLED = 'utter/pictures/UPDATE_PICTURE_FULFILLED'
// const UPDATE_QUERY = 'utter/pictures/UPDATE_QUERY'
// const UPDATE_QUERY_FULFILLED = 'utter/pictures/UPDATE_QUERY_FULFILLED'
const UPDATE_TRANSLATION = 'utter/pictures/UPDATE_TRANSLATION'
const UPDATE_TRANSLATION_FULFILLED =
  'utter/pictures/UPDATE_TRANSLATION_FULFILLED'
const LOAD_WORD_LIST = 'utter/pictures/LOAD_WORD_LIST'
const LOAD_WORD_LIST_FULFILLED = 'utter/pictures/LOAD_WORD_LIST_FULFILLED'
const UPDATE_WORD_LIST = 'utter/pictures/UPDATE_WORD_LIST'
const UPDATE_WORD_LIST_FULFILLED = 'utter/pictures/UPDATE_WORD_LIST_FULFILLED'
const UPDATE_REVIEW_LIST = 'utter/pictures/UPDATE_REVIEW_LIST'
const UPDATE_REVIEW_LIST_FULFILLED =
  'utter/pictures/UPDATE_REVIEW_LIST_FULFILLED'
const SEND_ROMANIZED = 'utter/pictures/SEND_ROMANIZED'
const SEND_ROMANIZED_FULFILLED = 'utter/pictures/SEND_ROMANIZED_FULFILLED'
const SEND_TRANSLATED = 'utter/pictures/SEND_TRANSLATED'
const SEND_TRANSLATED_FULFILLED = 'utter/pictures/SEND_TRANSLATED_FULFILLED'

export {
  LOAD_QUERY,
  LOAD_QUERY_FULFILLED,
  LOAD_QUESTION,
  LOAD_QUESTION_FULFILLED,
  LOAD_WORD_LIST,
  LOAD_WORD_LIST_FULFILLED,
  LOAD_ORIGINAL_WORD_LIST,
  LOAD_ORIGINAL_WORD_LIST_FULFILLED,
  UPDATE_ORIGINAL_WORD_LIST,
  UPDATE_ORIGINAL_WORD_LIST_FULFILLED,
  UPDATE_PICTURE,
  UPDATE_PICTURE_FULFILLED,
  // UPDATE_QUERY,
  // UPDATE_QUERY_FULFILLED,
  UPDATE_TRANSLATION,
  UPDATE_TRANSLATION_FULFILLED,
  UPDATE_WORD_LIST,
  UPDATE_WORD_LIST_FULFILLED,
  UPDATE_REVIEW_LIST,
  UPDATE_REVIEW_LIST_FULFILLED,
  SEND_ROMANIZED,
  SEND_ROMANIZED_FULFILLED,
  SEND_TRANSLATED,
  SEND_TRANSLATED_FULFILLED
}
