const LOAD = 'utter/pictures/LOAD'
const LOAD_FULFILLED = 'utter/pictures/LOAD_FULFILLED'
const LOAD_QUERY = 'utter/pictures/LOAD_QUERY'
const LOAD_QUERY_FULFILLED = 'utter/pictures/LOAD_QUERY_FULFILLED'
const LOAD_ORIGINAL_WORD_LIST = 'utter/pictures/LOAD_ORIGINAL_WORD_LIST'
const LOAD_ORIGINAL_WORD_LIST_FULFILLED =
  'utter/pictures/LOAD_ORIGINAL_WORD_LIST_FULFILLED'
const LOAD_WORD_LIST = 'utter/pictures/LOAD_WORD_LIST'
const LOAD_WORD_LIST_FULFILLED = 'utter/pictures/LOAD_WORD_LIST_FULFILLED'
const UPDATE_WORD_LIST = 'utter/pictures/UPDATE_WORD_LIST'
const UPDATE_WORD_LIST_FULFILLED = 'utter/pictures/UPDATE_WORD_LIST_FULFILLED'
const UPDATE_REVIEW_LIST = 'utter/pictures/UPDATE_REVIEW_LIST'
const UPDATE_REVIEW_LIST_FULFILLED =
  'utter/pictures/UPDATE_REVIEW_LIST_FULFILLED'
const SEND_ROMANIZED = 'utter/pictures/SEND_ROMANIZED'
const SEND_ROMANIZED_FULFILLED = 'utter/pictures/SEND_ROMANIZED_FULFILLED'
const SEND_TRANSLATED = 'utter/pictures/SEND_TRANSLATED'
const SEND_TRANSLATED_FULFILLED = 'utter/pictures/SEND_TRANSLATED_FULFILLED'

export {
  LOAD,
  LOAD_QUERY,
  LOAD_FULFILLED,
  LOAD_QUERY_FULFILLED,
  LOAD_WORD_LIST,
  LOAD_WORD_LIST_FULFILLED,
  LOAD_ORIGINAL_WORD_LIST,
  LOAD_ORIGINAL_WORD_LIST_FULFILLED,
  UPDATE_WORD_LIST,
  UPDATE_WORD_LIST_FULFILLED,
  UPDATE_REVIEW_LIST,
  UPDATE_REVIEW_LIST_FULFILLED,
  SEND_ROMANIZED,
  SEND_ROMANIZED_FULFILLED,
  SEND_TRANSLATED,
  SEND_TRANSLATED_FULFILLED
}
