const LOAD = 'utter/pictures/LOAD'
const LOAD_FULFILLED = 'utter/pictures/LOAD_FULFILLED'
const LOAD_QUERY = 'utter/pictures/LOAD_QUERY'
const LOAD_QUERY_FULFILLED = 'utter/pictures/LOAD_QUERY_FULFILLED'
const SEND_TRANSLATED = 'utter/pictures/SEND_TRANSLATED'
const SEND_TRANSLATED_FULFILLED = 'utter/pictures/SEND_TRANSLATED_FULFILLED'

export {
  LOAD,
  LOAD_QUERY,
  LOAD_FULFILLED,
  LOAD_QUERY_FULFILLED,
  SEND_TRANSLATED,
  SEND_TRANSLATED_FULFILLED
}
