import mongoose from "mongoose"
import faker from "faker"
import cuid from "cuid"
import {isEmpty} from "lodash"

import Course from "./course-model.js"
const ObjectId = mongoose.Types.ObjectId

const courseTitles = [
  "The Good Old Days",
  "The Lightning Thief ",
  "The Falling of Love Of Dusk ",
  "Something a bit different",
  "Throne of Glass  ",
  "The Book of Mormon ",
  "Prejudice by Jane Austen",
  "Palace of Spies ",
  "Going Over by Beth",
  "Papercuts Podcast ",
  "Men of Bronze",
  "NickersonShadows SpiveyBronze ",
  "Harry Potter and the Philosophers",
  "ChandlerMy Life as Emperor ",
  "Books You received As A Gift",
  "Yesterday by Scott WesterfeldI",
  "The Finest Hours by Michael",
  "Home Alone by John",
  "Chasing Vermeer by Blue ",
  "Crooked Kind of Perfect ",
  "BalliettCharlotte's Web",
  "Books That Made Me Smile",
  "Angelmaker by Nick Harkaway",
  "The Fiend in Human ",
  "John MacLachlan Gray",
  "The Air Loom Gang ",
  "The Big Sleep by Raymond ChandlerHe ",
  "Died With His Eyes Open",
  "Gibson and Murakami "
]

export const languageOptions = [
  "english US",
  "spanish-mexican",
  "spanish-peruvian",
  "portuguese-brazil",
  "australian",
  "english-uk",
  "spanish-castilian",
  "french",
  "italian",
  "portuguese-Portugal",
  "dutch",
  "finnish",
  "danish",
  "greek",
  "norwegian",
  "swedish",
  "albanian",
  "armenian",
  "eastern-armenian",
  "western-armenian",
  "basque",
  "breton",
  "catalan",
  "cornish",
  "estonian",
  "faroese",
  "flemish",
  "georgian",
  "gothic",
  "hungarian",
  "icelandic",
  "irish",
  "ladin",
  "ladino",
  "latvian",
  "lithuanian",
  "luxembourgish",
  "maltese",
  "manx",
  "occitan ",
  "romanian",
  "sami ",
  "lule-sami ",
  "northern-sami ",
  "southern-sami ",
  "ume",
  "scots",
  "scottish ",
  "welsh",
  "German",
  "small-german-dialects",
  "swiss-German",
  "indonesian",
  "korean",
  "thai",
  "vietnamese",
  "mongolian",
  "azerbaijani",
  "hawaiian",
  "kazakh",
  "ainu",
  "burmese",
  "cebuano",
  "dzongkha",
  "javanese",
  "karen ",
  "khmer",
  "kyrgyz",
  "laz",
  "lu",
  "malay",
  "maori",
  "marshallese",
  "nepali",
  "tagalog",
  "tibetan",
  "chinese-simplified",
  "chinese-traditional",
  "mandarin-spoken-only",
  "cantonese",
  "cantonese-jyutping",
  "ningbo-dialect",
  "taishanese",
  "hakka",
  "japanese",
  "kanji",
  "japanese-no-script",
  "bengali",
  "gujarati",
  "hindi",
  "telugu",
  "urdu",
  "marathi",
  "kannada",
  "malayalam",
  "pali",
  "punjabi",
  "sanskrit",
  "tamang",
  "tamil",
  "arabic",
  "arabic Alphabet",
  "classical-quranic-arabic",
  "egyptian-arabic",
  "gulf-khaliji-arabic",
  "iraqi-arabic",
  "levantine-arabic",
  "modern-standard-arabic-roman-alphabet",
  "north-african-maghrebi-arabic",
  "hebrew",
  "turkish",
  "aramaic",
  "kurdish",
  "persian",
  "yiddish",
  "russian",
  "bosnian",
  "croatian",
  "czech",
  "polish",
  "serbian",
  "bulgarian",
  "slovak",
  "slovenian",
  "ukrainian",
  "belarusian",
  "circassian ",
  "macedonian",
  "ossetic",
  "other-slavic",
  "coptic",
  "swahili",
  "afrikaans",
  "akan",
  "amharic",
  "hausa",
  "kaonde",
  "kinyarwanda",
  "luganda",
  "malagasy",
  "mandinka",
  "nyanja",
  "somali",
  "soninke",
  "wolof",
  "zulu",
  "latin",
  "ancient-greek",
  "cherokee",
  "algonquian",
  "alutiiq",
  "choctaw",
  "citizen-potawatomi",
  "greenlandic",
  "guarani",
  "inuktitut",
  "lakota",
  "nahuatl ",
  "quechua",
  "esperanto",
  "interlingua ",
  "klingon",
  "lojban",
  "north-america ",
  "south-america ",
  "australian",
  "europe",
  "german",
  "asia",
  "chinese",
  "indian",
  "middle-east",
  "Arabic",
  "Slavic",
  "africa",
  "classics",
  "native American",
  "constructed-languages"
]

export default {
  faker: (req, res, next) => {
    for (var i = 0; i < 1000; ++i) {
      var course = new Course()

      course.title = faker.random.arrayElement([
        "Aenean Donec venenatis",
        "Praesent egestas neque",
        "Fusce vel duii Fusce vel dui",
        "Nullam accumsan lorem",
        "Curabitur a felis",
        "Pellentesque auctor neque",
        "Fusce vel duFusce vel duii",
        "Mauris sollicitudin fermentum",
        "Suspendisse enim turpis",
        "Mauris sollicitudin fermentum",
        "Nullam nuNullam nulla ero eros"
      ])
      course.owner = faker.random.arrayElement([
        "5caa11c126bd462e4023657b",
        "5ccd04389b251025231a8446",
        "5ccd08c796e018284f6180a5",
        "5ccd041b9b251025231a8445",
        "5ccd0a0f96e018284f6180a6",
        "5ccd03d29b251025231a8444"
      ])
      course.mode = "edit"
      course.resource = faker.random.arrayElement([
        "top",
        "h-dog",
        "HELLO",
        "Bye",
        "_what_",
        "...nah",
        " ",
        " top "
      ])
      course.teachingLang = faker.random.arrayElement(languageOptions)
      course.usingLang = faker.random.arrayElement(languageOptions)
      course.subscribers = faker.random.number()
      course.courseId = cuid()
      course.title = faker.random.arrayElement(courseTitles)
      course.courseDescription = faker.lorem.paragraph()
      course.courseImage = faker.image.image()

      // console.log('course', course.levels[i]._id)
      course.save(function(err) {
        if (err) throw err
      })
    }
    res.json(course)
  }
}
