export const courseTitles = [
  "The Good Old Days",
  "The Lightning Thief ",
  "The Falling of Love Of Dusk ",
  "Something a bit different",
  "Throne of Glass  ",
  "The Book of Mormon ",
  "Prejudice by Jane Austen",
  "Palace of Spies ",
  "Going Over by Beth",
  "Papercuts Podcast ",
  "Men of Bronze",
  "NickersonShadows SpiveyBronze ",
  "Harry Potter and the Philosophers",
  "ChandlerMy Life as Emperor ",
  "Books You received As A Gift",
  "Yesterday by Scott WesterfeldI",
  "The Finest Hours by Michael",
  "Home Alone by John",
  "Chasing Vermeer by Blue ",
  "Crooked Kind of Perfect ",
  "BalliettCharlotte's Web",
  "Books That Made Me Smile",
  "Angelmaker by Nick Harkaway",
  "The Fiend in Human ",
  "John MacLachlan Gray",
  "The Air Loom Gang ",
  "The Big Sleep by Raymond ChandlerHe ",
  "Died With His Eyes Open",
  "Gibson and Murakami "
]

export const languageOptions = [
  "english US",
  "spanish-mexican",
  "spanish-peruvian",
  "portuguese-brazil",
  "australian",
  "english-uk",
  "spanish-castilian",
  "french",
  "italian",
  "portuguese-Portugal",
  "dutch",
  "finnish",
  "danish",
  "greek",
  "norwegian",
  "swedish",
  "albanian",
  "armenian",
  "eastern-armenian",
  "western-armenian",
  "basque",
  "breton",
  "catalan",
  "cornish",
  "estonian",
  "faroese",
  "flemish",
  "georgian",
  "gothic",
  "hungarian",
  "icelandic",
  "irish",
  "ladin",
  "ladino",
  "latvian",
  "lithuanian",
  "luxembourgish",
  "maltese",
  "manx",
  "occitan ",
  "romanian",
  "sami ",
  "lule-sami ",
  "northern-sami ",
  "southern-sami ",
  "ume",
  "scots",
  "scottish ",
  "welsh",
  "German",
  "small-german-dialects",
  "swiss-German",
  "indonesian",
  "korean",
  "thai",
  "vietnamese",
  "mongolian",
  "azerbaijani",
  "hawaiian",
  "kazakh",
  "ainu",
  "burmese",
  "cebuano",
  "dzongkha",
  "javanese",
  "karen ",
  "khmer",
  "kyrgyz",
  "laz",
  "lu",
  "malay",
  "maori",
  "marshallese",
  "nepali",
  "tagalog",
  "tibetan",
  "chinese-simplified",
  "chinese-traditional",
  "mandarin-spoken-only",
  "cantonese",
  "cantonese-jyutping",
  "ningbo-dialect",
  "taishanese",
  "hakka",
  "japanese",
  "kanji",
  "japanese-no-script",
  "bengali",
  "gujarati",
  "hindi",
  "telugu",
  "urdu",
  "marathi",
  "kannada",
  "malayalam",
  "pali",
  "punjabi",
  "sanskrit",
  "tamang",
  "tamil",
  "arabic",
  "arabic Alphabet",
  "classical-quranic-arabic",
  "egyptian-arabic",
  "gulf-khaliji-arabic",
  "iraqi-arabic",
  "levantine-arabic",
  "modern-standard-arabic-roman-alphabet",
  "north-african-maghrebi-arabic",
  "hebrew",
  "turkish",
  "aramaic",
  "kurdish",
  "persian",
  "yiddish",
  "russian",
  "bosnian",
  "croatian",
  "czech",
  "polish",
  "serbian",
  "bulgarian",
  "slovak",
  "slovenian",
  "ukrainian",
  "belarusian",
  "circassian ",
  "macedonian",
  "ossetic",
  "other-slavic",
  "coptic",
  "swahili",
  "afrikaans",
  "akan",
  "amharic",
  "hausa",
  "kaonde",
  "kinyarwanda",
  "luganda",
  "malagasy",
  "mandinka",
  "nyanja",
  "somali",
  "soninke",
  "wolof",
  "zulu",
  "latin",
  "ancient-greek",
  "cherokee",
  "algonquian",
  "alutiiq",
  "choctaw",
  "citizen-potawatomi",
  "greenlandic",
  "guarani",
  "inuktitut",
  "lakota",
  "nahuatl ",
  "quechua",
  "esperanto",
  "interlingua ",
  "klingon",
  "lojban",
  "north-america ",
  "south-america ",
  "australian",
  "europe",
  "german",
  "asia",
  "chinese",
  "indian",
  "middle-east",
  "Arabic",
  "Slavic",
  "africa",
  "classics",
  "native American",
  "constructed-languages"
]
