const LOAD_UTTERED_LIST_FULFILLED = 'utter/uttered/LOAD_UTTERED_LIST_FULFILLED'
const LOAD_UTTERED_LIST = 'utter/uttered/LOAD_UTTERED_LIST'
const UPDATE_UTTERED_LIST = 'utter/uttered/UPDATE_UTTERED_LIST'
const UPDATE_UTTERED_LIST_FULFILLED =
  'utter/uttered/UPDATE_UTTERED_LIST_FULFILLED'

export {
  LOAD_UTTERED_LIST,
  LOAD_UTTERED_LIST_FULFILLED,
  UPDATE_UTTERED_LIST,
  UPDATE_UTTERED_LIST_FULFILLED
}
