const COURSE_NAME_ASYNC_SUCCESS = 'utter/courses/COURSE_NAME_ASYNC_SUCCESS'
const COURSE_LANGUAGE = 'utter/courses/COURSE_LANGUAGE'
const COURSE_LANGUAGE_FULFILLED = 'utter/courses/COURSE_LANGUAGE_FULFILLED'
const REQUESTED_DOG = 'utter/courses/REQUESTED_DOG'
const REQUESTED_DOG_SUCCEEDED = 'utter/courses/REQUESTED_DOG_SUCCEEDED'
const REQUESTED_DOG_FAILED = 'utter/courses/REQUESTED_DOG_FAILED'
const FETCHED_DOG = 'utter/courses/FETCHED_DOG'
const FETCHED_COURSE_NAME = 'utter/courses/FETCHED_COURSE_NAME'
const REQUESTED_COURSE_NAME_SUCCEEDED =
  'utter/courses/REQUESTED_COURSE_NAME_SUCCEEDED'
const REQUESTED_COURSE_NAME_FAILED =
  'utter/courses/REQUESTED_COURSE_NAME_FAILED'

export {
  COURSE_LANGUAGE,
  COURSE_LANGUAGE_FULFILLED,
  COURSE_NAME_ASYNC_SUCCESS,
  FETCHED_DOG,
  FETCHED_COURSE_NAME,
  REQUESTED_COURSE_NAME_FAILED,
  REQUESTED_COURSE_NAME_SUCCEEDED,
  REQUESTED_DOG,
  REQUESTED_DOG_FAILED,
  REQUESTED_DOG_SUCCEEDED
}
