const ADD_CUID_TO_LEVELS = 'utter/courses/ADD_CUID_TO_LEVELS'
const ADD_LEVEL = 'utter/courses/ADD_LEVEL'
const COURSE_NAME_ASYNC_SUCCESS = 'utter/courses/COURSE_NAME_ASYNC_SUCCESS'
const COURSE_LANGUAGE = 'utter/courses/COURSE_LANGUAGE'
const COURSE_LANGUAGE_FULFILLED = 'utter/courses/COURSE_LANGUAGE_FULFILLED'
const FETCHED_COURSE_NAME = 'utter/courses/FETCHED_COURSE_NAME'
const REQUESTED_COURSE_NAME_SUCCEEDED =
  'utter/courses/REQUESTED_COURSE_NAME_SUCCEEDED'
const REQUESTED_COURSE_NAME_FAIL = 'utter/courses/REQUESTED_COURSE_NAME_FAIL'

//Create Course api
const CREATE_COURSE = 'utter/courses/CREATE_COURSE'
const CREATE_COURSE_SUCCESS = 'utter/courses/CREATE_COURSE_SUCCESS'
const CREATE_COURSE_FAIL = 'utter/courses/CREATE_COURSE_FAIL'

//Read Course api
const READ_COURSE = 'utter/courses/READ_COURSE'
const READ_COURSE_SUCCESS = 'utter/courses/READ_COURSE_SUCCESS'
const READ_COURSE_FAIL = 'utter/courses/READ_COURSE_FAIL'

//Update Course api
const UPDATE_COURSE = 'utter/courses/UPDATE_COURSE'
const UPDATE_COURSE_SUCCESS = 'utter/courses/UPDATE_COURSE_SUCCESS'
const UPDATE_COURSE_FAIL = 'utter/courses/UPDATE_COURSE_FAIL'

// Delete Course api

// Misc
const RESET_COURSE_CREATE_FORM = 'utter/courses/RESET_COURSE_CREATE_FORM'
const SAVE_FORM_TO_REDUX = 'utter/courses/SAVE_FORM_TO_REDUX'

export {
  ADD_CUID_TO_LEVELS,
  ADD_LEVEL,
  COURSE_LANGUAGE,
  COURSE_LANGUAGE_FULFILLED,
  COURSE_NAME_ASYNC_SUCCESS,
  FETCHED_COURSE_NAME,
  REQUESTED_COURSE_NAME_FAIL,
  REQUESTED_COURSE_NAME_SUCCEEDED,
  RESET_COURSE_CREATE_FORM,
  SAVE_FORM_TO_REDUX,
  //CRUD
  CREATE_COURSE,
  CREATE_COURSE_SUCCESS,
  CREATE_COURSE_FAIL,
  READ_COURSE,
  READ_COURSE_SUCCESS,
  READ_COURSE_FAIL,
  UPDATE_COURSE,
  UPDATE_COURSE_SUCCESS,
  UPDATE_COURSE_FAIL
}
