export const JOIN = "join"
export const GLOBAL_REGISTER = "global_register"
export const CREATE_USERZONE = "create_userzone"
export const ADD_CONTACT = "add_contact"
export const SEND_CONTACT_REQUEST = "send_contact_request"
