const CHANNEL_SELECT = 'utter/channels/CHANNEL_SELECT'
const CHANNEL_SELECT_FULFILLED = 'utter/channels/CHANNEL_SELECT_FULFILLED'
const LOAD = 'utter/channels/LOAD'
const LOAD_FULFILLED = 'utter/channels/LOAD_FULFILLED'
const LOAD_CHANNEL_ID = 'utter/channels/LOAD_CHANNEL_ID'
const LOAD_CHANNEL_ID_FULFILLED = 'utter/channels/LOAD_CHANNEL_ID_FULFILLED'
const SET_CHANNEL_SOCKET = 'utter/channels/SET_CHANNEL_SELECT'
const SET_CHANNEL_SOCKET_FULFILLED =
  'utter/channels/SET_CHANNEL_SELECT_FULFILLED'
const SORT = 'utter/channels/SORT'
const SORT_FULFILLED = 'utter/channels/SORT_FULFILLED'

export {
  CHANNEL_SELECT,
  CHANNEL_SELECT_FULFILLED,
  LOAD,
  LOAD_FULFILLED,
  LOAD_CHANNEL_ID,
  LOAD_CHANNEL_ID_FULFILLED,
  SORT,
  SORT_FULFILLED,
  SET_CHANNEL_SOCKET,
  SET_CHANNEL_SOCKET_FULFILLED
}
