const ADD_MESSAGE = "utter/socketio/ADD_MESSAGE"
const MESSAGE_FROM_CLIENT = "utter/socketio/MESSAGE_FROM_CLIENT"
const MESSAGE_FROM_SERVER = "utter/socketio/MESSAGE_FROM_SERVER"
const CREATE_ROOM = "utter/socketio/CREATE_ROOM"
const CREATE_ROOM_FAIL = "utter/socketio/CREATE_ROOM_FAIL"
const CREATE_ROOM_SUCCESS = "utter/socketio/CREATE_ROOM_SUCCESS"
const DELETE_AUDIO_BLOB = "utter/socketio/DELETE_AUDIO_BLOB"
const GET_ROOMS = "utter/socketio/GET_ROOMS"
const GET_ROOMS_FAIL = "utter/socketio/GET_ROOMS_FAIL"
const GET_ROOMS_SUCCESS = "utter/socketio/GET_ROOMS_SUCCESS"
const LOAD_AUDIO_BLOB = "utter/socketio/LOAD_AUDIO_BLOB"
const LOAD_SOCKET_NSPS = "utter/socketio/LOAD_SOCKET_NSPS"
const LOAD_SOCKET_NSPS_FAIL = "utter/socketio/LOAD_SOCKET_NSPS_FAIL"
const LOAD_SOCKET_NSPS_SUCCESS = "utter/socketio/LOAD_SOCKET_NSPS_SUCCESS"
const JOIN_ROOM = "utter/socketio/JOIN_ROOM"
const JOIN_ROOM_FAIL = "utter/socketio/JOIN_ROOM_FAIL"
const JOIN_ROOM_SUCCESS = "utter/socketio/JOIN_ROOM_SUCCESS"
const NSP_CONNECT = "utter/socketio/NSP_CONNECT"
const NSP_CONNECT_FAIL = "utter/socketio/NSP_CONNECT_FAIL"
const NSP_CONNECT_SUCCESS = "utter/socketio/NSP_CONNECT_SUCCESS"
const RECEIVE_AUDIO_BLOB = "utter/socketio/RECEIVE_AUDIO_BLOB"
const RECEIVE_AUDIO_BLOB_FAIL = "utter/socketio/RECEIVE_AUDIO_BLOB_FAIL"
const RECEIVE_AUDIO_BLOB_SUCCESS = "utter/socketio/RECEIVE_AUDIO_BLOB_SUCCESS"
const RECEIVE_MSG = "utter/socketio/RECEIVE_MSG"
const RECEIVE_MSG_FAIL = "utter/socketio/RECEIVE_MSG_FAIL"
const RECEIVE_MSG_SUCCESS = "utter/socketio/RECEIVE_MSG_SUCCESS"
const RECEIVE_ROOM_META = "utter/socketio/RECEIVE_ROOM_META"
const RECEIVE_ROOM_META_FAIL = "utter/socketio/RECEIVE_ROOM_META_FAIL"
const RECEIVE_ROOM_META_SUCCESS = "utter/socketio/RECEIVE_ROOM_META_SUCCESS"
const SEND_AUDIO_BLOB = "utter/socketio/SEND_AUDIO_BLOB"
const SEND_AUDIO_BLOB_FAIL = "utter/socketio/SEND_AUDIO_BLOB_FAIL"
const SEND_AUDIO_BLOB_SUCCESS = "utter/socketio/SEND_AUDIO_BLOB_SUCCESS"
const SEND_FILE = "utter/socketio/SEND_FILE"
const SEND_FILE_FAIL = "utter/socketio/SEND_FILE_FAIL"
const SEND_FILE_SUCCESS = "utter/socketio/SEND_FILE_SUCCESS"
const SEND_MSG = "utter/socketio/SEND_MSG"
const SEND_MSG_FAIL = "utter/socketio/SEND_MSG_FAIL"
const SEND_MSG_SUCCESS = "utter/socketio/SEND_MSG_SUCCESS"
const SEND_ROOM_META = "utter/socketio/SEND_ROOM_META"
const SEND_ROOM_META_FAIL = "utter/socketio/SEND_ROOM_META_FAIL"
const SEND_ROOM_META_SUCCESS = "utter/socketio/SEND_ROOM_META_SUCCESS"

export {
  ADD_MESSAGE,
  MESSAGE_FROM_CLIENT,
  MESSAGE_FROM_SERVER,
  CREATE_ROOM,
  CREATE_ROOM_FAIL,
  CREATE_ROOM_SUCCESS,
  DELETE_AUDIO_BLOB,
  GET_ROOMS,
  GET_ROOMS_FAIL,
  GET_ROOMS_SUCCESS,
  JOIN_ROOM,
  JOIN_ROOM_FAIL,
  JOIN_ROOM_SUCCESS,
  LOAD_AUDIO_BLOB,
  LOAD_SOCKET_NSPS,
  LOAD_SOCKET_NSPS_FAIL,
  LOAD_SOCKET_NSPS_SUCCESS,
  NSP_CONNECT,
  NSP_CONNECT_FAIL,
  NSP_CONNECT_SUCCESS,
  RECEIVE_AUDIO_BLOB,
  RECEIVE_AUDIO_BLOB_FAIL,
  RECEIVE_AUDIO_BLOB_SUCCESS,
  RECEIVE_MSG,
  RECEIVE_MSG_FAIL,
  RECEIVE_MSG_SUCCESS,
  RECEIVE_ROOM_META,
  RECEIVE_ROOM_META_FAIL,
  RECEIVE_ROOM_META_SUCCESS,
  SEND_AUDIO_BLOB,
  SEND_AUDIO_BLOB_FAIL,
  SEND_AUDIO_BLOB_SUCCESS,
  SEND_FILE,
  SEND_FILE_FAIL,
  SEND_FILE_SUCCESS,
  SEND_MSG,
  SEND_MSG_FAIL,
  SEND_MSG_SUCCESS,
  SEND_ROOM_META,
  SEND_ROOM_META_FAIL,
  SEND_ROOM_META_SUCCESS
}
