const LOAD_USER_PROFILE = 'utter/connections/LOAD_USER_PROFILE'
const LOAD_USER_PROFILE_FULFILLED =
  'utter/connections/LOAD_USER_PROFILE_FULFILLED'

export {LOAD_USER_PROFILE, LOAD_USER_PROFILE_FULFILLED}
